### ISSUE TITLE
Rename project repo to adlibs from ad-libs.js

### ISSUE THREAD

**Issue by jeffreytgilbert** [conversant/adlibs#18]
adlibs is installed as npm install adlibs. The repo has a different name. Can we update these to match and get some consistency going?

**Comment by j-brown** [comment]
@jeffreytgilbert do you want it to be ad-libs or adlibs, when npm install is run?

**Comment by jeffreytgilbert** [comment]
Same as its always been. This should be transparent to implementers, but the public repo name would be different than they expect which is ok. That change just needs to be passed to npm so they know how to redirect the fetch.

**Comment by j-brown** [comment]
Work complete. We'll need to update the pkg.json with this change in the next release.

**Comment by jeffreytgilbert** [comment]
Thanks JB

**Comment by jeffreytgilbert** [comment]
https://www.npmjs.com/package/adlibs still links to the wrong repo. Please update.

**Comment by j-brown** [comment]
@jeffreytgilbert  Per my comment, we'll tie the pkg update to the next release.
